#!/bin/bash

. ../../../conf
. ../../conf
. ../conf
. ./conf

if [ ! -e $BASE_DIR ]; then
    mkdir -p $BASE_DIR
fi
cp ./Dockerfile $BASE_DIR
cp -r ./script $BASE_DIR
cp -r ./files $BASE_DIR
cp -r ./sql $BASE_DIR

