version: '2'

networks:
  multiplication:
    driver: bridge
volumes:
  rabbitmqdata:
  pgdata:
services:
    multiplication-db:
      image: postgres:latest
      build:
          context: ./multiplication-db
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=multiplication
        - POSTGRES_PASSWORD=multiplication
        - POSTGRES_DB=multiplication
      volumes:
        - 'pgdata:/var/lib/postgresql/data'
      networks:
        - multiplication

    rabbitmq:
      image: 'rabbitmq:3-management'
      ports:
        - 5672:5672
        - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
      volumes:
        - 'rabbitmqdata:/var/lib/rabbitmq'
      networks:
        - multiplication