version: '2'

networks:
  multiplication:
    driver: bridge
volumes:
  multiplication:
services:
  multiplication-db:
    image: multiplication-db:latest
    build:
        context: ./multiplication-db
    ports:
        - 5432:5432

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
    volumes:
      - 'multiplication:/bitnami'
  multiplication:
    image: 'multiplication:latest'
    build:
        context: ./multiplication
    ports:
        - 8080:8080
  gamification:
    image: 'gamification:latest'
    build:
        context: ./gamification
    ports:
        - 28081:8081
